from scanner.core import Finding, Severity, ScanSession

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": [("Server", "cloudflare"), ("CF-RAY", "")],
        "cookies": ["__cfduid", "cf_clearance", "__cf_bm"],
        "body": ["Attention Required! | Cloudflare", "cf-browser-verification"],
    },
    "AWS WAF": {
        "headers": [("x-amzn-RequestId", "")],
        "cookies": ["awsalb", "awsalbcors"],
        "body": [],
    },
    "Akamai": {
        "headers": [("X-Akamai-Transformed", "")],
        "cookies": ["AkamaiEdge"],
        "body": ["Access Denied - Akamai"],
    },
    "Imperva/Incapsula": {
        "headers": [("X-CDN", "Incapsula")],
        "cookies": ["incap_ses_", "visid_incap_"],
        "body": ["Incapsula incident", "powered by Incapsula"],
    },
    "Sucuri": {
        "headers": [("X-Sucuri-ID", ""), ("X-Sucuri-Cache", "")],
        "cookies": ["sucuri_cloudproxy"],
        "body": ["Access Denied - Sucuri"],
    },
    "ModSecurity": {
        "headers": [("Server", "Mod_Security"), ("Server", "NOYB")],
        "cookies": [],
        "body": ["Mod_Security", "This error was generated by Mod_Security"],
    },
    "F5 BIG-IP ASM": {
        "headers": [("X-WA-Info", "")],
        "cookies": ["TS01", "BIGipServer"],
        "body": ["The requested URL was rejected"],
    },
    "Barracuda": {
        "headers": [("barra_counter_session", "")],
        "cookies": ["barra_counter_session"],
        "body": ["Barracuda Web Application Firewall"],
    },
    "Fortinet FortiWeb": {
        "headers": [],
        "cookies": ["FORTIWAFSID"],
        "body": ["FortiWeb", ".fwb_err_page"],
    },
    "DDoS-Guard": {
        "headers": [("Server", "ddos-guard")],
        "cookies": ["__ddg"],
        "body": [],
    },
}

WAF_TRIGGER_PAYLOADS = [
    "<script>alert(1)</script>",
    "' OR 1=1 --",
    "../../etc/passwd",
    "${7*7}",
    "{{7*7}}",
]


def detect_waf(session: ScanSession) -> list[str]:
    detected = []
    resp = session.get(session.config.target)
    if not resp:
        return detected

    for waf_name, sigs in WAF_SIGNATURES.items():
        if (_check_headers(resp, sigs["headers"]) or
                _check_cookies(resp, sigs["cookies"]) or
                _check_body(resp, sigs["body"])):
            detected.append(waf_name)

    if not detected:
        for payload in WAF_TRIGGER_PAYLOADS:
            trigger_resp = session.get(
                "{}/?test={}".format(session.config.target, payload),
                allow_redirects=False,
            )
            if not trigger_resp:
                continue
            if trigger_resp.status_code in (403, 406, 429, 503):
                for waf_name, sigs in WAF_SIGNATURES.items():
                    if _check_body(trigger_resp, sigs["body"]):
                        detected.append(waf_name)
                        break
                if not detected and trigger_resp.status_code == 403:
                    detected.append("Unknown WAF")
                break

    return list(set(detected))


def _check_headers(resp, header_checks):
    for name, value in header_checks:
        actual = resp.headers.get(name, "")
        if actual and (not value or value.lower() in actual.lower()):
            return True
    return False


def _check_cookies(resp, cookie_names):
    cookie_str = "; ".join(c.name for c in resp.cookies).lower()
    return any(name.lower() in cookie_str for name in cookie_names)


def _check_body(resp, body_patterns):
    text = resp.text.lower()
    return any(p.lower() in text for p in body_patterns)
